### PR TITLE
Add file is empty action

### PR DESCRIPTION
**Pull request by fxedel**
Adds an action that checks whether the configured (static) files are empty, e.g. an application's error log file.

### CODE REVIEW

**Review by sebastianfeldmann — CHANGES_REQUESTED** [review]
Hi Felix, thanks you for you pull request.

Please add a unit test for your action.

**Review by sebastianfeldmann — APPROVED** [review]
Nice thanks

**Comment by fxedel** [comment]
Thanks for merging! The `@since` PHPDoc parameter is still `TODO`, will you change it when you release the next version? Or should I update it myself (e.g. in the File DoesNotContainRegex action PR) to `5.4.0`?

**Comment by sebastianfeldmann** [comment]
I'll change it ;)

**Pull request merged**
