### PR TITLE
WIP: Add support for filtering staged files by directory

### PR DESCRIPTION
**Pull request by juho-jaakkola**
Preliminary work for the issue #114 just to exchange ideas an opinions.

This PR adds a support for filtering the staged files for the `pre-commit` hook based on their location in the file tree.

## Example use case:

A project has been split into new code (i.e. `src/`) and legacy code (i.e. `lib/functions/`). The project owner wants to have strict coding style rules for the new code, but does not want to enforce these rules for the legacy code.

So they would add two new entries in the `captainhook.json` file. The additional filter `in-dir:src/` for the staged files, and a condition that the action should be run only if there indeed are staged files from that directory.
```json
{
  "action": "php-cs-fixer {$STAGED_FILES|of-type:php|in-dir:src/}",
  "options": [],
  "conditions": [
    {
      "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\OfType",
      "args": [
        "php"
      ]
    },
    {
      "exec": "\\CaptainHook\\App\\Hook\\Condition\\FileStaged\\InDirectory",
      "args": [
        "src"
      ]
    }
  ]
}

```
Now a single commit would be able to contain changes both to new and legacy code, but the coding style rules would be enforced only for the new code.

## Stuff to think about

While testing this, I realized that apparently the conditions are joined with `OR` and not with `AND`. This would be a problem for this particular use case, because one of the conditions might pass even though there wouldn't be any files to check when both of the filters get used. And not giving an explicit file list as parameter to php-cs-fixer would cause it to fall back to lint every single file in the whole project.

I wonder if the OR-combining is there by design?

Another topic is that I wonder if the new `in-dir` filter is generic enough use case to hard-code it into captainhook. I guess an ideal solution would be to expose a public API for defining new classes implementing the `Placeholder` interface. This way it would be possible to define whatever crazy custom rules for each project separately.

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
Here are my thoughts

> Now a single commit would be able to contain changes both to new and legacy code, but the coding style rules would be enforced only for the new code.
> 

I really like the `in-dir` filter thing.

> ## Stuff to think about
> While testing this, I realized that apparently the conditions are joined with `OR` and not with `AND`. This would be a problem for this particular use case, because one of the conditions might pass even though there wouldn't be any files to check when both of the filters get used. And not giving an explicit file list as parameter to php-cs-fixer would cause it to fall back to lint every single file in the whole project.
> 
> I wonder if the OR-combining is there by design?

Yes the `OR` combination is by design. You can always archive an `AND` combination by creating a custom Condition that checks both conditions at once.
But it would be nice to have that build in. I'm thinking about a `Condition\Group` that you can configure to contain multiple `Conditions`. But I'm not sure yet if this makes sense.

> Another topic is that I wonder if the new `in-dir` filter is generic enough use case to hard-code it into captainhook. I guess an ideal solution would be to expose a public API for defining new classes implementing the `Placeholder` interface. This way it would be possible to define whatever crazy custom rules for each project separately.

The filter is a nice addition and yes registering custom placeholders would be a nice addition as well.

Since Conditions for now are merged with `OR` this pull request will not fix your issue a 100%.
You would have to create a custom Condition that checks both `of-type` and `in-directory`.
At least until I figured out a way to combine Conditions with `AND` as well.

**Comment by heiglandreas** [comment]
What about an `And`-Condition that internally contains a list of other Conditions? 

```php
class And implements Condition
{
    public function isTrue(IO $io, Repository $repository): bool
    {
        /** @var Condition $condition */
        foreach ($this->list as $condition) {
            if (false === $condition->isTrue($io, $repository)) {
                return false;
            }
        }
        return true;
    }
}
```

And while we're at it also create the `Or`-Condition like this:

```php
class Or implements Condition
{
    public function isTrue(IO $io, Repository $repository): bool
    {
        /** @var Condition $condition */
        foreach ($this->list as $condition) {
            if (true === $condition->isTrue($io, $repository)) {
                return true;
            }
        }
        return false;
    }
}
```

Shall I check how to iomplement soemthing like that?

**Comment by sebastianfeldmann** [comment]
@heiglandreas you are more than welcome to implement something like that :)

**Comment by heiglandreas** [comment]
> @heiglandreas you are more than welcome to implement something like that :)

See #118 :wink:

**Comment by sebastianfeldmann** [comment]
I copied both the condition and the placeholder stuff over to master and added some unit tests ;)
Your changes are included in version 5.6.1

In the upcoming days we will figure out how we will handle the `AND` condition implementation.
As soon this is done your issue will be fixed.

For now I will close this PR

Thank you for opening it and starting the discussion about the condition issue.

**Pull request closed without merging**
