### PR TITLE
Add branch EnsureNaming action

### PR DESCRIPTION
**Pull request by fxedel**
Adds an action that checks whether the current git branch matches a specific pattern (useful for `post-checkout`).

### CODE REVIEW

**Review by sebastianfeldmann — CHANGES_REQUESTED** [review]
Hi Felix, thanks for the pull request.

If I understand this correctly this Action should prevent you from committing into certain branches. Or better only allow you to commit to certain branches.

The naming of the Action is a bit off then. Please provide a more clear Action name like `RestrictCommitsTo` or something similar.

**Review by sebastianfeldmann — CHANGES_REQUESTED** [review]
Please add a required unit test for this action

**Comment by fxedel** [comment]
As for the naming: This action is originally meant for `post-checkout` hook to ensure a proper branch naming (e.g., when you want to include the ticket name in the branch name). However, it does also make sense using this action in `pre-commit` and `pre-push`, for similar reasons.

`RestrictCommitsTo` would be a bit too specific then, in my opinion. I added the `Branch` directory which leads to this fully qualified class name: `CaptainHook\App\Hook\Branch\Action\Regex`. Maybe better something like `CaptainHook\App\Hook\Git\Action\RestrictBranchName`? I'm not happy with this either, as the whole `CaptainHook\App\Hook\Message` namespace actually also had to be under `CaptainHook\App\Hook\Git`.

**Comment by sebastianfeldmann** [comment]
Ah I see.
The only thing you can do then is to fail after the branch is already created. The only way to prevent commits in a branch with a wrong name is with a `pre-commit` hook. But if you want to give immediate feedback after creating/checking out the branch you can do this in a `post-checkout` hook.

I would argue that you could use the same action in `post-checkout` and `pre-commit`.

Maybe something like `EnsureBranchNaming` there should be an option to exclude branches from that rule like `master`,  `main`,  `integration` or something.

```
"regex": "#[a-z]+-[0-9]+#i",
"ignore": [
    "master",
    "integration"
]
```

If you do it in a `pre-commit` hook you maybe do not want to exclude branches :/

**Comment by fxedel** [comment]
Correct, with `post-checkout`, we can show an error message when the branch name doesn't match the pattern, but we can't prevent creating that branch. That's how we're currently using it (with another Githook library though, we're currently migrating to CaptainHook).

As for the ignore option: What about simply changing the Regex: `/master|integration|[a-z]+-[0-9]+/i`? That would spare us the extra option.

**Comment by sebastianfeldmann** [comment]
You are right extending the regex makes much more sense

**Review by sebastianfeldmann — APPROVED** [review]
Looks great. I would suggest we merge pull request after pull request and rebase each pull request after the previous one is merged :)

Let me know if you have trouble rebasing to `origin/master`.

**Pull request merged**
