### PR TITLE
[WIP] Acceptance tests with Codeception

### PR DESCRIPTION
**Pull request by ramsey**
As I neared completion on #125, I wanted a way to write acceptance tests for the functionality—tests that actually simulated a user working in a repo and executing `git commit`, etc. to run the hooks. I took a look at Codeception, and it appeared to offer some functionality that could help in this respect, so I decided to start playing with it to see what I could come up with.

This PR includes work from #125, but the last few commits are all related to the Codeception work. Take a look through it and let me know if this looks like something you'd like to include and expand on for more acceptance testing.

### CODE REVIEW

**Comment by sebastianfeldmann** [comment]
I really like he idea of functional / acceptance tests.

I've not used codeception yet, I'll have a look at it, but sounds very interesting :)

**Comment by ramsey** [comment]
> I've not used codeception yet, I'll have a look at it, but sounds very interesting

I've honestly never used it before this. 😄 

Using it might actually be overkill and more difficult to maintain in the long run (since you'd effectively have two test suites using two different testing libraries). Now that I have this working, I think I could easily re-work it into a base PHPUnit test case class to support the acceptance testing and get rid of Codeception altogether. (I'm kind of eager to do that, actually. 😉 )

Thoughts?

**Comment by sebastianfeldmann** [comment]
That would be seeeeeeeet

**Comment by ramsey** [comment]
Interesting that he uses PHPT tests for that. I didn't know that.

**Pull request closed without merging**
